### ISSUE TITLE
ust_node stops running

### ISSUE THREAD

**Issue by Ainhoamm1** [BasB1/hokuyo_ust#1]
Hi! I'm trying to run a node with laser Hokuyo UST-10LN and this is the only one package I found that could work with it. If you know any other option easier please let me know. 

When I start running the launcher ust_node, after some time it stops running with the following message:

Traceback (most recent call last):
  File "/home/ainhoa/catkin_ws/src/hokuyo_ust/src/ust_node.py", line 116, in <module>
    data = ust.get_measures()
  File "/home/ainhoa/catkin_ws/src/hokuyo_ust/src/ust_node.py", line 81, in get_measures
    measurements = [(int(data[i:i+4],16), int(data[i+4:i+8],16))  for i in range(0, len(data)-8, 8)]
ValueError: invalid literal for int() with base 16: '0LN:'
[ust_node-2] process has died [pid 4369, exit code 1, cmd /home/ainhoa/catkin_ws/src/hokuyo_ust/src/ust_node.py __name:=ust_node __log:=/home/ainhoa/.ros/log/e11f8092-9a0e-11ec-84a1-74c63bbfb2a1/ust_node-2.log].
log file: /home/ainhoa/.ros/log/e11f8092-9a0e-11ec-84a1-74c63bbfb2a1/ust_node-2*.log

 Also, it doesn't let me show the scan topin in RVIZ. 
I don't know much about Python so I don't know how to fix it. Any help would be appreciated :)

**Comment by Amelghet** [comment]
I have the same error with UST05 ln as [Ainhoamm1](https://github.com/Ainhoamm1) any help please

**Comment by Ainhoamm1** [comment]
> I have the same error with UST05 ln as [Ainhoamm1](https://github.com/Ainhoamm1) any help please
@Amelghet 

From https://gist.github.com/Fabien-B/87e57316e5b265ca42d179f3c860f879#gistcomment-4086021 

Check this: 

 "So that anyone looking here would know, for UST-20LN version of this code only changes needed are:
line 87: if len(data[1]) == 541 to line 87: if len(data[1]) == 1081 since for 20LN the resolution is higher, and
line 16: MESURE_LENGHT = 4359 (= 541 steps * 8 bytes + 31 bytes ) to line 16: MESURE_LENGHT = 8679 (= 1081 steps * 8 bytes + 31 bytes )"

I used the same as 20LN. I read about the 05LN:" The  sensor  has  1081  measurement steps ".
